### ISSUE TITLE
i run the code in replit give me this error Traceback (most recent call last):   File "dcbot/bot.py", line 19, in <module>     MY_GUILD = discord.Object(id=SERVER_ID)   File "/home/runner/BingGPT-Discord-Bot-1/venv/lib/python3.10/site-packages/discord/object.py", line 95, in __init__     id = int(id) TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

### ISSUE THREAD

**Issue by n4free** [ediziks/BingGPT-Discord-Bot#3]
Traceback (most recent call last):
  File "dcbot/bot.py", line 19, in <module>
    MY_GUILD = discord.Object(id=SERVER_ID)
  File "/home/runner/BingGPT-Discord-Bot-1/venv/lib/python3.10/site-packages/discord/object.py", line 95, in __init__
    id = int(id)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

**Comment by ediziks** [comment]
Most probably related to `SERVER_ID` in `.env` file. Be sure that you put the server id you try to invite the bot.

**Comment by n4free** [comment]
I add server id the cod already in this server

**Comment by ediziks** [comment]
The bot may already be in the server, inviting the bot to the server is a separate process from running the bot. Just the `SERVER_ID` has to be as explained in the instructions, also it has to be a `.env` file, not `.env.example`. Does that solve your case?

**Comment by n4free** [comment]
no to really , are you try run the project in replit before

**Comment by ediziks** [comment]
No, but in your case it's definitely related to server_id variable in `.env` file. Maybe it's not placed correctly. It should be without quotes or angle brackets similar to this;
```
SERVER_ID=123456789012345678
```

**Comment by n4free** [comment]
replit didn't have .env it have Secrets 
![image](https://user-images.githubusercontent.com/121499962/227728848-6aa1553c-d790-4e9b-a543-578b548691ed.png)

**Comment by ediziks** [comment]
I don't know how you try to run but it's worked here on the first try. The issue is still ongoing on your side?

<img width="1398" alt="image" src="https://user-images.githubusercontent.com/54022220/227731128-281e968a-7779-434b-9cc2-e331f644f104.png">

**Comment by unkeyn** [comment]
I have the same problem, my env looks like this. also file is ".env"
![WindowsTerminal_b8RvrUERkm](https://user-images.githubusercontent.com/88308876/228132254-d10068fd-8d1a-4f8e-8dd8-125e947c6f62.png)
![Notepad_bD8Axn7Dvf](https://user-images.githubusercontent.com/88308876/228132261-7f16126b-ea19-491d-853c-5fcc9f4c7224.png)

**Comment by ediziks** [comment]
@unkeyn Thanks for letting me know about the issue. I have just pushed a recent change on that. Can try pulling the repository again and let me know if it works or not?

**Comment by unkeyn** [comment]
@ediziks I downloaded it again, the problem was not solved. here is a screenshot of the error. thanks for fast respond
![изображение](https://user-images.githubusercontent.com/88308876/228190266-c2f92d9f-865d-4316-a569-66558786dcd3.png)

**Comment by ediziks** [comment]
@unkeyn can you approve that the name of your environment file is `.env`? Because it seems like `my_secret.env` in the screenshot you shared previously.

**Comment by unkeyn** [comment]
@ediziks here
![изображение](https://user-images.githubusercontent.com/88308876/228193704-9a023ecb-a37b-4244-b2d6-6170a5792942.png)

**Comment by ediziks** [comment]
Ok, I assume it's related to the name of the file. It still seems like `secret.env` which is supposed to be only `.env`.

**Comment by unkeyn** [comment]
@ediziks now this is working, thanks!
